- hosts: localhost
  tasks:
          - package:
                  name: "httpd"
                  state: "present"
          - copy:
                  content: "write your content"
                  dest: "/var/www/html/index.html"
          - firewalld:
                  port: "80/tcp"
                  state: enabled
                  immediate: yes
                  permanent: yes
          - service:
                  name: "httpd"
                  state: started
                  enabled: yes
